### PR TITLE
Feat/allow omb start time

### PR DESCRIPTION
**Pull request by jerabaul29**
Make it possible to consider only messages received after a given time point. Very convenient since instruments are usually switched on a bit before deployment.

Update both the omb reader and the omb example. Example works fine, as well as a larger use case I am working on, with the local installation on my machine.

### CODE REVIEW

**Comment by gauteh** [comment]
Looks very convenient. Just make sure that there is not an almost equally easy way to do this on the xarray dataset?

**Comment by knutfrode** [comment]
Xarray is extremely powerful, but it can be a bit challenging to find the right command to achieve something specific.
Thus making many convenience methods may be tempting, but I agree with Gaute that it is generally better if things can be done with lower level commands, i.e. directly with Xarray. Thus a strategy we have adopted lately, is to rather disseminate examples demonstrating how to achieve certain things, instead of making even more convenience methods.

Not saying that this is necessarily the case here, but it is good to check if the desired can be achieved with Xarray, and then potentially make an example to demonstrate this.

**Comment by gauteh** [comment]
Very possible that this is difficult to do with xarray, the second best option is to add a method to Trajan to do this. Then all types of drifter data will benefit from it. Again, I'm not totally opposed to your solution, just trying to make things more general if possible.

**Comment by gauteh** [comment]
Merged :)

**Pull request merged**
