### PR TITLE
Feat/spectrashow

### PR DESCRIPTION
**Pull request by jerabaul29**
Add a simple function to perform plots of spectra from xarrays that follow the trajan convention. The example generate a figure like:

Screenshot from 2024-07-19 17-03-55

with a single line of code:

```python
plot_trajan_spectra(xr_data)
```

### CODE REVIEW

**Comment by gauteh** [comment]
Great! I think it would be best to put this in the accessor type style as the other trajan plotting. Maybe this should even be a variable accessor, then you could do:

```
ds.elevation_spectrum.plot()
```

**Comment by gauteh** [comment]
This can happen if the plots are not closed in the tests. Then the next test will try to re-use the axes.

**Comment by gauteh** [comment]
Yes, I think we can merge first and fix later. Although there's always the risk that it is forgotten :D Not the end of the world either. 

I agree that it is nice to skip the specific variable names we have chosen. Since it is a specific variable still, maybe it should be something like: ds.waves.E.plot(). There may also be something to win here using the xarray-cf package, I always find the long standard names variables so tedious to write...

**Comment by gauteh** [comment]
I added you as maintainer, since I am still on vacation you can merge it.

**Comment by knutfrode** [comment]
Yes, I also find it very tedious to write unnecessarily long names.
On the other hand, the value of the uniqueness and standardness of CF standard name is no great that I have stopped making shorthand aliases, as these will always be ad-hoc and software/person/project-specific, and add volume and complexity to the codebase.
Thus I would in fact favor e.g.
`ds.waves.energy_density_spectrum.plot()`
over
`ds.waves.E.plot()`
I am anyway fine with making shorthand aliases if you prefer.

---------

And this is also a very important question: `I guess there is a question of what trajan wants to focus on`
It is always very tempting to push in a lot of features that one need right now, or for a specific project or task. But in the long run I believe it is healthier for any software to stick to its core tasks. This is why TrajAn was extracted from OpenDrift in the first place, so that OpenDrift can focus on making trajectory simulations, whereas TrajAn can focus on the analysis, and then also applicable to non-OpenDrift data such as buoy measurements.
So there is an important question whether code for handling/analysing/plotting of wave spectra should be within TrajAn, or whether one should rather make a small stand-alone package for this, and then rather let TrajAn use this though some thin wrapper.

Those were my 2 cents, happy to hear any disagreements :-)

**Comment by gauteh** [comment]
> And this is also a very important question: `I guess there is a question of what trajan wants to focus on` It is always very tempting to push in a lot of features that one need right now, or for a specific project or task. But in the long run I believe it is healthier for any software to stick to its core tasks. This is why TrajAn was extracted from OpenDrift in the first place, so that OpenDrift can focus on making trajectory simulations, whereas TrajAn can focus on the analysis, and then also applicable to non-OpenDrift data such as buoy measurements. So there is an important question whether code for handling/analysing/plotting of wave spectra should be within TrajAn, or whether one should rather make a small stand-alone package for this, and then rather let TrajAn use this though some thin wrapper.
> 
> Those were my 2 cents, happy to hear any disagreements :-)

I also agree about this, but favor pragmatism: especially if we stick to ds.waves.elevation_density_spectrum or ds.elevation_density_spectrum (which may be provided by cf-xarray) it is easy to separate this into a new package later if it outgrows trajan. 

> Thus I would in fact favor e.g.
> `ds.waves.energy_density_spectrum.plot()`
> over
> `ds.waves.E.plot()`
> I am anyway fine with making shorthand aliases if you prefer.

Yes, you are right of course. It is the only solution. Maybe I should just get proper auto-completion in my editor.

**Comment by gauteh** [comment]
Yes.

**Pull request merged**
