### PR TITLE
traj: change seltime to sel, more generic and works on all coordinates.

### PR DESCRIPTION
**Pull request by gauteh**
Can also change into a `maptraj` method that applies a function separately on each trajectory. This makes all methods in 1d work on 2d trajs, making everything easier.

### CODE REVIEW

**Comment by knutfrode** [comment]
Good!
Is `seltime` kept for backwards compatibility, or does it serve different purpose?

**Comment by gauteh** [comment]
> Is `seltime` kept for backwards compatibility, or does it serve different purpose?

Yes, I was first thinking to remove it. But keeping it means that the user doesn't have to remember the name of the time variable, not sure if it is still worth it?

**Comment by knutfrode** [comment]
No strong opinion, but perhaps better to skip `seltime`, and let users get some drill in using `self.time_varname` ?

**Comment by gauteh** [comment]
I think the alternative is to do:

```
ds.traj.sel(time=slice(t0, t1))
```

no one is going to bother with:

```
ds.traj.sel({self.ds.traj.time_varname : slice(t0, t1)})
```

**Comment by knutfrode** [comment]
Yes, I agree.
The first version is what a user can/will use (API), whereas the second version is what we can use within TrajAn codebase.
But then still open if we should keep `seltime` or not. Maybe we can come back to this decision later, after gaining some experience with actual usage.

**Comment by gauteh** [comment]
Yes :+1:

**Pull request merged**
